### ISSUE TITLE
Chain multiple messages.

### ISSUE THREAD

**Issue by brenohq** [kinni/fb-bot-framework#3]
Hello! I'm trying to chain some messages. For example:

```javascript
bot.sendTextMessage(userId, "Message 1...");
bot.sendTextMessage(userId, "Message 2...");
```

I need these messages to be sent in order. "Message 1..." and then "Message 2...".

I've tried this, but unsuccessful.

```javascript
bot.sendTextMessage(userId, "Message 1...").then(() => {
    bot.sendTextMessage(userId, "Message 2...");
})
```

Thanks for the nice job man, bye!

**Comment by ghost** [comment]
Hey brenohq,

you can use the cb function

```
function cb() {
 bot.sendTextMessage(userId, "Message 2");
}

bot.sendTextMessage(userId, "Message 1", null, cb");
```
cheers,

franzus

**Comment by brenohq** [comment]
@franzus888 Tranks bro!
