### ISSUE TITLE
Can't send menus

### ISSUE THREAD

**Issue by norrisboat** [kinni/fb-bot-framework#8]
For some reason all the other types of messages work but menus don't seem to be working for me.
Here is my code:

    var text = "How can I help you today?";
	var buttons = [
	    {
	        "type": "postback",
	        "title": "Start a New Order",
	        "payload": "start_order"
	    },
	    {
	        "type": "postback",
	        "title": "Call Us",
	        "payload": "call_us"
	    },
	    {
	        "type": "web_url",
	        "title": "View Website",
	        "url": "http://something.com/"
	    },
	    {
	        "type": "web_url",
	        "title": "Download App",
	        "url": "http://something.com/"
	    }
	];
	bot.sendButtonMessage(usersId, text, buttons);

**Comment by norrisboat** [comment]
I was sending more than the required number of menus. Thanks for this awesome library.

**Comment by ViolentCrumble** [comment]
Just had this issue, So i'm guessing the limit is 3? Can we get this added to the docs please?
